#!/usr/bin/env bash
#This script transfers a file to the client server

file_path=$1
host_ip=$2
user_name=$3
id_file=$4

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -T -i "$id_file" "$file_path" "$user_name@$host_ip:~"
fi