#!/usr/bin/env bash
#This script installs nginx on the server

status=$(dpkg --status nginx | grep Status)
idea="Status: install ok installed"

if [ "$status" != "$idea" ];
then
	echo "not installed but installing"
	sudo apt-get update
	sudo apt-get -y install nginx
fi

printf "server { 
       listen 80;
       server_name dmurenzi.tech 35.174.204.133 3.83.18.3 35.175.132.191;

       add_header X-Served-By \$hostname;

       location / {
       		return 200 'Hello World!';
       }
}\n" > /tmp/hbnb_static.conf
sudo cp /tmp/hbnb_static.conf /etc/nginx/conf.d/hbnb_stat.conf
rm /tmp/hbnb_static.conf
sudo nginx -s reload
