#!/usr/bin/env bash
#This script installs nginx on the server

status=$(dpkg --status nginx | grep Status)
idea="Status: install ok installed"

if [ "$status" != "$idea" ];
then
    sudo apt-get update
    sudo apt-get -y install nginx
fi


printf 'server { 
       listen 80;
       server_name dmurenzi.tech;

       location / {
              return 200 "Hello World!";
       }
}' > /tmp/hbnb_static.conf
sudo cp /tmp/hbnb_static.conf /etc/nginx/conf.d/hbnb_stat.conf
rm /tmp/hbnb_static.conf
sudo nginx -s reload
