#!/usr/bin/env bash
#This script installs nginx on the server

status=$(dpkg --status nginx | grep Status)
idea="Status: install ok installed"

if [ "$status" != "$idea" ];
then
	echo "not installed but installing"
	sudo apt-get update
	sudo apt-get -y install nginx
fi

printf "%sCeci n%sest pas une page%s" '"' "'" '"'> tem
sudo cp tem /var/www/html/custom_404.html
rm tem
printf 'server { 
       listen 80;
       server_name dmurenzi.tech;

       location /redirect_me {
       		return 301 "https://www.youtube.com/watch?v=qh2-TGUlwu4";
       }
       error_page 404 /custom_404.html;
       
       location /custom_404.html {
       		internal;
		root /var/www/html;
}
}\n' > /tmp/hbnb_static.conf
sudo cp /tmp/hbnb_static.conf /etc/nginx/conf.d/hbnb_stat.conf
rm /tmp/hbnb_static.conf
sudo nginx -s reload
